- set-fact: 
    build_number: "{{ lookup('env','BUILD_NUMBER') }}"

- name: ansible create EC2
  ec2:
    key_name: nyuelin
    instance_type: t2.micro
    image: ami-04328208f4f0cf1fe
    wait: yes
    wait_timeout: 500
    count: 1
    instance_tags:
      app: test-deployment
      version: "{{ build_number }}"
  register: ec2